// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmttgfqtfxfmdhhubtnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtdHRnZnF0ZnhmbWRoaHVidG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNTU3MDAsImV4cCI6MjA2MjkzMTcwMH0.VTbp3GGBpHSJGHRYd9Xkt5_embGL9THOEYWyAXsHLBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);